export enum PlayerState {
  IDLE_UP = "IDLE_UP",
  IDLE_DOWN = "IDLE_DOWN",
  IDLE_LEFT = "IDLE_LEFT",
  IDLE_RIGHT = "IDLE_RIGHT",

  WALK_UP = "WALK_UP",
  WALK_DOWN = "WALK_DOWN",
  WALK_LEFT = "WALK_LEFT",
  WALK_RIGHT = "WALK_RIGHT",
}
